# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'
  DemoResourceGroupName: 'ColinsDemoRG'

stages:
- stage: Build
  jobs:
  - job: 'BuildAndPublish'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/*[Tt]ests/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Pipeline.Workspace)/output'
        zipAfterPublish: True
  
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Pipeline.Workspace)'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
         SimpleDotNetCoreApp.ARM/**
         SimpleDotNetCoreApp.Selenium/bin/Release/**
        TargetFolder: '$(Pipeline.Workspace)/output'

#    - task: PublishPipelineArtifact@1
#      inputs:
#        targetPath: '$(Pipeline.Workspace)/output'
#        artifact: 'drop'
    - publish: '$(Pipeline.Workspace)/output'
      artifact: drop

- stage: Dev
  jobs:
    - deployment: DeployWebsite
      pool:
        vmImage: 'ubuntu-latest'
      variables:
        WebAppName: 'ColinsYAMLDemoDev'
      environment: Dev
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: drop
              #- task: DownloadPipelineArtifact@1
              #  inputs:
              #    buildType: 'current'
              #    artifactName: 'drop'
              #    targetPath: '$(System.ArtifactsDirectory)/drop'
              - task: AzureResourceManagerTemplateDeployment@3
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: 'Colin Beales MSDN(7e006c82-4480-45f0-93c2-502b8f4f757a)'
                  subscriptionId: '7e006c82-4480-45f0-93c2-502b8f4f757a'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: '$(DemoResourceGroupName)'
                  location: 'UK South'

                  templateLocation: 'Linked artifact'
                  csmFile: '$(Pipeline.Workspace)/drop/SimpleDotNetCoreApp.ARM/WebSite.json'
                  csmParametersFile: '$(Pipeline.Workspace)/drop/SimpleDotNetCoreApp.ARM/WebSite.parameters.json'
                  overrideParameters: '-hostingPlanName "webapphostingplan" -webSiteName $(WebAppName) -skuName "F1" -skuCapacity 1'
                  deploymentMode: 'Incremental'
              
              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'Colin Beales MSDN(7e006c82-4480-45f0-93c2-502b8f4f757a)'
                  appType: 'webApp'
                  WebAppName: '$(WebAppName)'
                  packageForLinux: '$(Pipeline.Workspace))/**/*.zip'

- stage: QA
  jobs:
    - deployment: DeployWebsite
      pool:
        vmImage: 'ubuntu-latest'
      variables:
        WebAppName: 'ColinsYAMLDemoQA'
      environment: QA
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadPipelineArtifact@1
                inputs:
                  buildType: 'current'
                  artifactName: 'drop'
                  targetPath: '$(System.ArtifactsDirectory)/drop'
              - task: AzureResourceManagerTemplateDeployment@3
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: 'Colin Beales MSDN(7e006c82-4480-45f0-93c2-502b8f4f757a)'
                  subscriptionId: '7e006c82-4480-45f0-93c2-502b8f4f757a'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: '$(DemoResourceGroupName)'
                  location: 'UK South'

                  templateLocation: 'Linked artifact'
                  csmFile: '$(System.ArtifactsDirectory)/drop/SimpleDotNetCoreApp.ARM/WebSite.json'
                  csmParametersFile: '$(System.ArtifactsDirectory)/drop/SimpleDotNetCoreApp.ARM/WebSite.parameters.json'
                  overrideParameters: '-hostingPlanName "webapphostingplan" -webSiteName $(WebAppName) -skuName "F1" -skuCapacity 1'
                  deploymentMode: 'Incremental'
              
              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'Colin Beales MSDN(7e006c82-4480-45f0-93c2-502b8f4f757a)'
                  appType: 'webApp'
                  WebAppName: '$(WebAppName)'
                  packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'

- stage: Prod
  jobs:
    - deployment: DeployWebsite
      pool:
        vmImage: 'ubuntu-latest'
      variables:
        WebAppName: 'ColinsYAMLDemoProd'
      environment: Prod
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadPipelineArtifact@1
                inputs:
                  buildType: 'current'
                  artifactName: 'drop'
                  targetPath: '$(System.ArtifactsDirectory)/drop'
              - task: AzureResourceManagerTemplateDeployment@3
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: 'Colin Beales MSDN(7e006c82-4480-45f0-93c2-502b8f4f757a)'
                  subscriptionId: '7e006c82-4480-45f0-93c2-502b8f4f757a'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: '$(DemoResourceGroupName)'
                  location: 'UK South'

                  templateLocation: 'Linked artifact'
                  csmFile: '$(System.ArtifactsDirectory)/drop/SimpleDotNetCoreApp.ARM/WebSite.json'
                  csmParametersFile: '$(System.ArtifactsDirectory)/drop/SimpleDotNetCoreApp.ARM/WebSite.parameters.json'
                  overrideParameters: '-hostingPlanName "webapphostingplan" -webSiteName $(WebAppName) -skuName "F1" -skuCapacity 1'
                  deploymentMode: 'Incremental'
              
              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'Colin Beales MSDN(7e006c82-4480-45f0-93c2-502b8f4f757a)'
                  appType: 'webApp'
                  WebAppName: '$(WebAppName)'
                  packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'

