# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- download:

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '34697803-e92f-4c40-bdad-47390909183b'
    definition: '483'
    buildVersionToDownload: 'latest'
    artifactName: 'drop'
    targetPath: '$(Pipeline.Workspace)'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

